[application]

# dioxus project name
name = "do-it-ui"

# default platfrom
# you can also use `dioxus serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Dioxus | An elegant GUI library for Rust"

[web.watcher]

index_on_404 = true

watch_path = ["."]

# include `assets` in web platform
[web.resource]

# CSS style file
style = [
    "uno.css",
    "tailwind.min.css",
]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[application.plugins]

available = true

required = []
